{
    "private": {
        "docker_repository_url": "815644216915.dkr.ecr.ap-southeast-1.amazonaws.com",
        "aws_region": "ap-southeast-1",
        "jenkins_cloud": "kubernetes",
        "agent_image": "178092210163.dkr.ecr.ap-southeast-1.amazonaws.com/jenkins-agent-jdk17-maven:20260629-v9",
        "chart_name": "astrox-helm-chart",
        "namespaces": "test",
        "add_java_jar": "ADD {project}/build/libs/*.jar /app/app.jar",
        "gradle_ins": "${jradle_path}/bin/gradle ${project}:clean --refresh-dependencies ${project}:build -x test",

        "env_tier": "test",
        "deploy_agent_image": "alpine/k8s:1.28.4",
        "node_select": "environment: sit",
        "kubeconfig_credential_id": "ofc-test",
        "nfs_server": "fs-0575ae6fd27edf058.efs.ap-southeast-1.amazonaws.com",
        "log_nfs_server": "fs-078f16b1172edf396.efs.ap-southeast-1.amazonaws.com",
        "limits_cpu": "1",
        "limits_mem": "2G",
        "requests_cpu": "0.1",
        "requests_mem": "0.2G",
        "kind_name": "deployment",
        "min_replicas": "1",
        "max_replicas": "2",
        "no_ingress": "false",
    },

    "sit-java-apisix-route": {
        "github_url": "https://github.com/jackchen9919/test.git",
        "node_ins": "npm run build",
        "nodejs_version": "NodeJS 16.14.1",
        "app_name": "apisix-route-test",
        "project": "apisix-route-test",
        "project_type": "nginx",
        "replicas": "1",
        "http_port": "8080",
        "actuator_port": "8080",
        "ingress_hosts": "apisix-route-test.astroxs.com",
        "ingress_paths": "/*",
        "no_ingress": "false",
        "websocket_port": "null",
        "skywalking_enabled": "false",
        "namespaces": "apisix-route-test",
    },

    "sit-java-apisix-route-2": {
        "github_url": "https://github.com/jackchen9919/test.git",
        "node_ins": "npm run build",
        "nodejs_version": "NodeJS 16.14.1",
        "app_name": "apisix-route-test",
        "project": "apisix-route-test",
        "project_type": "nginx",
        "replicas": "1",
        "http_port": "8080",
        "actuator_port": "8080",
        "ingress_hosts": "apisix-route-test.astroxs.com",
        "ingress_paths": "/*",
        "no_ingress": "false",
        "websocket_port": "null",
        "skywalking_enabled": "false",
        "namespaces": "apisix-route-test",
    },
}
