server {
    listen 8080;
    root /app/;
    index index.html index.htm;
	add_header X-Frame-Options "SAMEORIGIN";

    location / {
        expires      -1;
        try_files $uri $uri/ ${uri}.html /index.html;
    }
    location ~* ^.+\.(eot|ttf|otf|woff|svg)$ {
        access_log  off;
        expires max;
    }
}