{
    "private": {
        "docker_repository_url": "815644216915.dkr.ecr.ap-southeast-1.amazonaws.com",
        "aws_region": "ap-southeast-1",
        "jenkins_cloud": "pre-eks",
        "agent_image": "alpine/k8s:1.28.4",
        "chart_name": "astrox-helm-chart",
        "env_tier": "uat",
        "namespaces": "uat",
        "limits_cpu": "1",
        "limits_mem": "4G",
        "requests_cpu": "0.1",
        "requests_mem": "0.2G",
        "node_select": "environment: global-uat",
        "kubeconfig_credential_id": "ofc-test",
        "nfs_server": "fs-0575ae6fd27edf058.efs.ap-southeast-1.amazonaws.com",
        "log_nfs_server": "fs-078f16b1172edf396.efs.ap-southeast-1.amazonaws.com",
        "add_java_jar": "ADD {project}/build/libs/*.jar /app/app.jar",
        "gradle_ins": "${jradle_path}/bin/gradle ${project}:clean --refresh-dependencies ${project}:build -x test",
        "kind_name": "deployment",
        "min_replicas": "1",
        "max_replicas": "100",
        "no_ingress": "false",
    },

    "apisix-route": {
        "app_name": "apisix-route-test",
        "project": "apisix-route-test",
        "project_type": "nginx",
        "replicas": "1",
        "http_port": "8080",
        "actuator_port": "8080",
        "ingress_hosts": "apisix-route-test-uat.astroxs.com",
        "ingress_paths": "/*",
        "no_ingress": "false",
        "websocket_port": "null",
        "skywalking_enabled": "false",
        "namespaces": "apisix-route-test-uat",
    },
}
