{{- if .Values.canary }}
{{- if .Values.canary.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appname }}-canary
  namespace: {{ .Values.namespace }}
  labels:
    project-type: {{ .Values.project_type }}
spec:
  ports:
    {{- range $key := .Values.ports }}
    - name: {{ $key.name }}
      protocol: {{ $key.protocol }}
      port: {{ $key.port }}
      targetPort: {{ $key.port }}
    {{- end }}
  selector:
    appname: {{ .Values.appname }}-canary
  type: ClusterIP
  clusterIP: None
{{- end }}
{{- end }}
