{
    "private": {
        "docker_repository_url": "FILL_IN_ECR_REGISTRY_PROD.dkr.ecr.FILL_IN_REGION.amazonaws.com",
        "aws_region": "FILL_IN_REGION",
        "jenkins_cloud": "FILL_IN_PROD_JENKINS_CLOUD",
        "agent_image": "FILL_IN_PROD_AGENT_IMAGE",
        "chart_name": "astrox-helm-chart",
        "env_tier": "prod",
        "namespaces": "prod25",
        "limits_cpu": "2",
        "limits_mem": "6G",
        "requests_cpu": "1",
        "requests_mem": "4G",
        "autoscaling_enable": "true",
        "node_select": "environment: prod",
        "KUBECONFIG": "/data/kubeconfig/prod",
        "nfs_server": "fs-01a6f2dbba9fc7418.efs.us-west-2.amazonaws.com",
        "log_nfs_server": "fs-0e46303df2944183f.efs.us-west-2.amazonaws.com",
        "add_java_jar": "ADD {project}/build/libs/*.jar /app/app.jar",
        "gradle_ins": "${jradle_path}/bin/gradle ${project}:clean --refresh-dependencies ${project}:build -x test",
        "kind_name": "deployment",
        "min_replicas": "2",
        "max_replicas": "10",
        "no_ingress": "false",
        "websocket_port": "null",
        "skywalking_enabled": "false",
    },
}
